### PR TITLE
Updated Routing API usage for Laravel 4.1

### PR DESCRIPTION
**Pull request by rmasters**
The Routing API's changed a bit in 4.1. This uses the new API but it's incompatible with 4.0.x. I don't know if you want to maintain a separate branch for 4.0.x after 4.1's been released or have a single file that works for both?

### CODE REVIEW

**Comment by sebklaus** [comment]
Hi Ross,

sorry for not getting back, sooner. Thank you very much for your work!
I'll have a look over the weekend. I'll probably try to make it work in one branch/ package, just to make it as easy as possible for everyone.

Cheers,
Seb

**Comment by sebklaus** [comment]
Hi Ross,

finally managed to spend some time on this.
Would you mind giving my `laravel4.1` branch a go?
`git pull https://github.com/sebklaus/profiler laravel4.1`

It still works on 4.0.x.
I'll try and set up a Laravel 4.1 environment, once I'm home.

Cheers,
Seb

**Comment by rmasters** [comment]
Hi Seb, 

Your branch works fine in our 4.1 app - thanks!

**Comment by sebklaus** [comment]
Changes pulled into `laravel4.1` branch.
Will be merged into `master` and tagged as `v1.7.1`.

**Pull request closed without merging**
