### PR TITLE
[BugFix] getMemoryUsage()

### PR DESCRIPTION
**Pull request by wells**
Both getMemoryUsage() and formatBytes() need to be static for
getCounts() to return a value for the memory usage.

### CODE REVIEW

**Comment by sebklaus** [comment]
Hi Brian, thanks for the pull request. I hadn't noticed any issues with the output of the used memory.
I get a value on all my test and production systems. What happens for you? Empty value?
Cheers, Seb

**Comment by wells** [comment]
Yeah, it shows something like MEM __ until I found and changed the methods to static calls. The methods do return a correct value, but they do not return a value in the closure found in getCounts(). FYI, I'm using laravel 4.0.7.

**Comment by sebklaus** [comment]
Thanks for getting back to me. Could you tell me a bit about the system you are running Laravel on? OS, PHP version, etc? I'd like to set up a test environment to see, if I can replicate the issue. This particular part hasn't been touched. It's still the original from juy/profiler.

**Comment by wells** [comment]
Ubuntu 12.04.3 LTS, PHP 5.3.10-1ubuntu3.8 with Suhosin-Patch, Apache 2.2.22, need anything else?

**Comment by sebklaus** [comment]
Perfect! Thanks Brian.

Now that you drew my attention to this part of the script, I noticed some more things, like `$bytes` being overwritten in the `formatBytes()` function. I also noticed that in `getCounts()` the call is done via `Profiler::getMemoryUsage()`, which is unnecessary (wrong). Would you mind using my original version and just changing this particular call to `$this->getMemoryUsage()` to see if that fixes your issue? If not, I'll run up a system with PHP 5.3 to do some testing.

**Comment by wells** [comment]
Changing to `$this->getMemoryUsage()` in `getCounts()` actually throws an error: 

**Error**
"Using $this when not in object context"

---

`Profiler::getMemoryUsage()`, that is located in the current code of `getCounts()`, also appears to error out without my provided code changes. This error is not visible as the views catch the error.

---

FYI, I just added the removal of `$bytes = memory_get_usage();` from `formatBytes()` in my pull request.

**Comment by wells** [comment]
Also, There really is nothing wrong with changing `getMemoryUsage()` and `formatBytes()` to static as they are only called by `getCounts()` or one calls the other in this package.

**Comment by sebklaus** [comment]
Thanks again, Brian. Hope this fixes your issues. Must have been something specific to your setup, as I couldn't replicate the issue, even on PHP 5.3 (a later version you are using, though). Going static doesn't seem to make a difference, as you said.

**Pull request merged**
